name: ArrowGun
main: DeBePlugins\ArrowGun\ArrowGun
version: DeBe
api: [1.6.0]
author: DeBe

commands:
 arrowgun:
  permission: debe.arrowgun.cmd
  description: ArrowGun - Command
  usage: /ArrowGun

permissions:
 debe:
  default: op
  description: DeBePlugins
  children:
   debe.arrowgun.cmd:
   	default: true
    description: ArrowGun - Command